<a href="https://colab.research.google.com/github/SourabhiDunung/Deep_Learning/blob/main/Ex1_TensorFlow_overview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Sourabhi Dunung

Roll No: UEC2021211

Class: E&Tc B DL3

Experiment 1: Tensorflow Overwiew

In [ ]:
import tensorflow as tf

Addition operation

In [ ]:
a1= tf.constant([[1,2,3],[4,7,13]])
b1= tf.constant([[2,4,7],[5,8,90]])
c1= tf.add(a1,b1)
print(c1)

tf.Tensor(
[[  3   6  10]
 [  9  15 103]], shape=(2, 3), dtype=int32)


Substraction operation

In [ ]:
p1= tf.constant([[1,2,3],[4,7,13]])
q1= tf.constant([[2,4,7],[5,8,90]])
r1= tf.subtract(p1,q1)
print(r1)

tf.Tensor(
[[ -1  -2  -4]
 [ -1  -1 -77]], shape=(2, 3), dtype=int32)


Multiply

In [ ]:
x1= tf.constant([[1,2,3],[4,7,13]])
y1= tf.constant([[2,4,7],[5,8,90]])
z1= tf.multiply(x1,y1)
print(z1)

tf.Tensor(
[[   2    8   21]
 [  20   56 1170]], shape=(2, 3), dtype=int32)


Matrix Multipilication

In [ ]:
s1= tf.constant([[1,2,3],[4,7,13]])
t1= tf.constant([[4,7,9],[2,4,7],[5,8,90]])
u1= tf.matmul(s1,t1)
print(u1)

tf.Tensor(
[[  23   39  293]
 [  95  160 1255]], shape=(2, 3), dtype=int32)


row wise or column wise addition

In [ ]:
l1= tf.constant([[1,2,3],[4,7,13]])
i1=tf.reduce_sum(l1) #complete matrix
i2=tf.reduce_sum(l1,0) #column 1
i3=tf.reduce_sum(l1,1) #column 2
print(i1)
print(i2)
print(i3)

tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor([ 5  9 16], shape=(3,), dtype=int32)
tf.Tensor([ 6 24], shape=(2,), dtype=int32)


declaring the function

In [ ]:
def myfun():
 print("Hello there!")

In [ ]:
myfun()

Hello there!


with arguremnt

In [ ]:
def my_function(fname):
 print(fname + " from cummins")
my_function("Sourabhi")
my_function("Mayuri")
my_function("Nandini")

Sourabhi from cummins
Mayuri from cummins
Nandini from cummins


using cProfile

In [ ]:
import cProfile

In [ ]:
def wrapper():
    my_function("Sourabhi")
    my_function("Mayuri")
    my_function("Nandini")

In [ ]:
cProfile.run("wrapper()")

Sourabhi from cummins
Mayuri from cummins
Nandini from cummins
         96 function calls in 0.002 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        3    0.000    0.000    0.002    0.001 <ipython-input-56-7b11f2dc2e00>:1(my_function)
        1    0.000    0.000    0.002    0.002 <ipython-input-58-1ad41a9ff9ea>:1(wrapper)
        1    0.000    0.000    0.002    0.002 <string>:1(<module>)
        7    0.000    0.000    0.002    0.000 iostream.py:195(schedule)
        6    0.000    0.000    0.000    0.000 iostream.py:308(_is_master_process)
        6    0.000    0.000    0.000    0.000 iostream.py:321(_schedule_flush)
        6    0.000    0.000    0.002    0.000 iostream.py:384(write)
        7    0.000    0.000    0.000    0.000 iostream.py:91(_event_pipe)
        7    0.002    0.000    0.002    0.000 socket.py:543(send)
        7    0.000    0.000    0.000    0.000 threading.py:1102(_wait_for_tstate_lock)
        7   